# Generated by Django 5.1.4 on 2024-12-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('tel', models.CharField(blank=True, max_length=17, null=True)),
                ('Pazivnoy', models.CharField(blank=True, max_length=8, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Qarz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.PositiveIntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('date_creat', models.DateField(auto_now_add=True)),
                ('date_edit', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'qarz',
            },
        ),
    ]
