# Generated by Django 5.1.4 on 2024-12-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Pazivnoy',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
