# Generated by Django 5.1.4 on 2024-12-25 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_employee_pazivnoy_alter_employee_tel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Pazivnoy',
            new_name='pazivnoy',
        ),
    ]
