# Generated by Django 5.1.4 on 2024-12-25 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_pazivnoy_employee_pazivnoy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qarz',
            old_name='date_creat',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='qarz',
            name='date_edit',
        ),
    ]
